services:
  node:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./:/app:cached
      - ./build/entrypoint.sh:/entrypoint.sh